#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_gl options')

	grp.add_option('--enable-static-gl', action='store_true', dest='GL_STATIC', default=False,
		help = 'enable direct linking to opengl [default: %(default)s]')

	# stub
	return

def configure(conf):
	conf.env.GL_STATIC = conf.options.GL_STATIC
	if conf.env.GL_STATIC:
		conf.check(lib='GL')

	if conf.env.DEST_OS2 == 'android':
		conf.check_cc(lib='log')

def build(bld):
	libs = [ 'ref_common', 'engine_includes', 'werror', 'yy_thunks' ]
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes', 'vgl_shim' ]
	else:
		libs += [ 'public', 'M' ]

	source = bld.path.ant_glob(['*.c', 'gl2_shim/*.c'])
	includes = ['.']
	libpath = []
	extra_libs = []
	extra_defines = []

	if bld.env.RAYTRACING:
		rtgl1_sdk = os.environ.get('RTGL1_SDK_PATH', r'E:\Xash-RT\RayTracedGL1')
		includes.append(os.path.join(rtgl1_sdk, 'Include'))
		libpath.extend([
			os.path.join(rtgl1_sdk, 'Build', 'Release'),
			os.path.join(rtgl1_sdk, 'Build', 'x64-Release'),
			os.path.join(rtgl1_sdk, 'Build', 'Debug'),
			os.path.join(rtgl1_sdk, 'Build', 'x64-Debug'),
		])
		extra_libs.extend(['RayTracedGL1', 'opengl32', 'user32', 'gdi32'])
		extra_defines.extend(['XASH_RAYTRACING=1', 'XASH_GL_STATIC=1'])

		def copy_rtgl1_dll(bld_ctx):
			import shutil
			src_dll = os.path.join(rtgl1_sdk, 'Build', 'Release', 'RayTracedGL1.dll')
			if not os.path.exists(src_dll):
				src_dll = os.path.join(rtgl1_sdk, 'Build', 'x64-Release', 'RayTracedGL1.dll')
			if os.path.exists(src_dll):
				dst = bld_ctx.bldnode.abspath()
				shutil.copy(src_dll, dst)
				src_ffx = os.path.join(os.path.dirname(src_dll), 'amd_fidelityfx_vk.dll')
				if os.path.exists(src_ffx):
					shutil.copy(src_ffx, dst)

		bld.add_post_fun(copy_rtgl1_dll)

	targets = {
		'ref_gl': {
			'enable':  bld.env.GL,
			'libs':    (['GL'] if bld.env.GL_STATIC else []) + extra_libs,
			'defines': (['XASH_GL_STATIC=1'] if bld.env.GL_STATIC else []) + extra_defines,
		},
		'ref_gles1': {
			'enable':  bld.env.NANOGL,
			'libs':    ['DL', 'nanogl', 'LOG'],
			'defines': ['XASH_NANOGL=1'],
		},
		'ref_gles2': {
			'enable':  bld.env.GLWES,
			'libs':    ['DL', 'gl-wes-v2', 'LOG'],
			'defines': ['XASH_WES=1'],
		},
		'ref_gl4es': {
			'enable':  bld.env.GL4ES,
			'libs':    ['DL', 'gl4es', 'LOG'],
			'defines': ['XASH_GL_STATIC=1', 'XASH_GL4ES=1'],
		},
		'ref_gles3compat': {
			'enable':  bld.env.GLES3COMPAT,
			'libs':    [],
			'defines': ['XASH_GLES3COMPAT=1'],
		},
	}

	for k,v in targets.items():
		if not v['enable']:
			continue

		bld.shlib(source = source,
			target = k,
			includes = includes,
			libpath = libpath,
			lib = v['libs'],
			use = libs,
			defines = v['defines'] + ['REF_DLL=1'],
			install_path = bld.env.LIBDIR)
